enum DefaultExceptionTypes {
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    REQUIRE_SUBSCRIPTION = 'REQUIRE_SUBSCRIPTION',
    NOT_FOUND = 'NOT_FOUND',
    BAD_REQUEST = 'BAD_REQUEST',
    CONFLICT = 'CONFLICT',
    ABORT_REQUEST = 'ABORT_REQUEST',
    SERVER_ERROR = 'SERVER_ERROR',
    SERVER_UNAVAILABLE ="SERVER_UNAVAILABLE",
    UNKNOWN_ERROR = 'UNKNOWN_ERROR'
}

export default DefaultExceptionTypes;