import { StringsType } from "./StringsKeys";

const en: StringsType = {
  french: "French",
  english: "English",
  hello: "Hello",
  dashbord: "Dashbord",
  other: "Other",
  failedGettingUserRole: "Failed getting user role",
  backToHome: "Back to home",
  pageNotFound: "Page not found",
  WeCouldntFindThePageYouAreLookingFor: "We couldn't find the page you are looking for.",
  internalServerError: "Internal server error",
  oopsSomethingWentWrong: "Oops, something went wrong",
  youAreNotAuthorized: "You are not authorized to access this page",
  youDonTHavePermissionToAccessThisPage: "You don't have permission to access this page",
  welcomeTo: "Welcome to",
  pleaseSignIn: "Please sign-in to your account and start the adventure",
  password: "Password",
  rememberMe: "Remember me",
  credentials: "Credentials",
  badCredentials: "Bad credentials",
  emailOrPasswordInvalid: "Email or Password is invalid",
  forgotPassword: "Forgot password",
  login: "Login",
  newOnOurPlatform: "New on our platform",
  createAnAccount: "Create an account",
  or: "or",
  errorOccurred: "An error occurred",
  unexpectedOrNetworkError: "Unexpected or network error",
  unauthorizedAction: "Unauthorized action",
  subscriptionRequired: "Subscription required",
  resourceNotFound: "Resource not found",
  invalidInfos: "Invalid infos",
  conflictEncountered: "Conflict encountered",
  unavailableServer: "Unavailable server",
  logoutFailed: "Logout failed",
  logout: "Logout",
};

export default en;
