import { StringsType } from "./StringsKey";

const fr: StringsType = {
  french: "Français",
  english: "Anglais",
  hello: "Bonjour",
  dashboard:"Tableau de Board",
  other: "Autre",
  failedGettingUserRole: "Échec de la récupération du rôle de l'utilisateur",
  backToHome: "Retour à l'accueil",
  pageNotFound: "Page non trouvée",
  WeCouldNotFindThePageYouAreLookingFor: "Nous n'avons pas pu trouver la page que vous recherchez.",
  internalServerError: "Erreur interne du serveur",
  oopsSomethingWentWrong: "Oups, quelque chose s'est mal passé",
  youAreNotAuthorized: "Vous n'êtes pas autorisé à accéder à cette page",
  youDonTHavePermissionToAccessThisPage: "Vous n'avez pas la permission d'accéder à cette page",
  welcomeTo: "Bienvenue à",
  pleaseSignIn: "Veuillez vous connecter à votre compte et commencer l'aventure",
  password: "Mot de passe",
  rememberMe: "Se souvenir de moi",
  credentials: "Informations d'identification",
  badCredentials: "Authentification échouée. Email ou mot de passe invalide.",
  emailOrPasswordInvalid: "Email ou mot de passe invalide",
  forgotPassword: "Mot de passe oublié",
  login: "Se connecter",
  newOnOurPlatform: "Nouveau sur notre plateforme",
  createAnAccount: "Créer un compte",
  or: "ou",
  errorOccurred: "Une erreur s'est produite",
  unexpectedOrNetworkError: "Erreur inattendue ou réseau",
  unauthorizedAction: "Action non autorisée",
  subscriptionRequired: "Abonnement requis",
  resourceNotFound: "Ressource non trouvée",
  invalidInfos: "Informations invalides",
  conflictEncountered: "Conflit rencontré",
  unavailableServer: "Serveur non disponible",
  logoutFailed: "Échec de la déconnexion",
  logout: "Déconnexion",
  externalResourceUnavailable: "Ressource externe non disponible, veuillez réessayer ou réessayer plus tard.",
  unexpectedError: "Erreur inattendue, veuillez réessayer ou réessayer plus tard.",
  requiredField: "Ce champ est requis",
  invalidEmail: "Email invalide",
  invalidPassword: "Mot de passe invalide",
  email: "Email",
  failed: "Échoué",
  userAvatar: "Avatar de l'utilisateur",
  operationFailed: "Opération échouée",
  FailedToLogoutUser: "Échec de la déconnexion de l'utilisateur",
  tryAgain: "Réessayer",
  thisIsAnError: "Ceci est une erreur",
};

export default fr;
