enum SessionStorageExceptionTypes {
    STORE_AUTH_DATAS_REPOSITORY_REQUIRED = 'STORE_AUTH_DATAS_REPOSITORY_REQUIRED',
    FAILED_TO_SAVE_AUTH_DATAS = 'FAILED_TO_SAVE_AUTH_DATAS',
    FAILED_TO_REMOVE_AUTH_DATAS = 'FAILED_TO_REMOVE_AUTH_DATAS',
}

export default SessionStorageExceptionTypes;